- name: create infra certificate authorities
  shell: echo '{{ lookup('template', '../templates/ca_csr.j2', convert_data=False) }}' | bin/cfssl gencert -initca - | bin/cfssljson -bare "{{ item }}" -
  args:
    chdir: ../secret/ssl
    creates: "{{ item }}.pem"
  with_items:
    - infra/etcd-ca

- name: create Kubernetes certificate authorities
  shell: echo '{{ lookup('template', '../templates/ca_csr.j2', convert_data=False) }}' | bin/cfssl gencert -initca - | bin/cfssljson -bare "{{ item }}" -
  args:
    chdir: ../secret/ssl
    creates: "{{ item }}.pem"
  with_items:
    - kubernetes/etcd-ca
    - kubernetes/apiserver-ca

- template:
    src: ../templates/ca_config.j2
    dest: ../secret/ssl/ca_config.json
