---
# Start VMs
- hosts: localhost
  connection: local
  vars:
    - num_worker_nodes: "{{ (desired_num_worker_nodes | int) - (groups['worker_nodes'] | length) }}"
  roles:
    - infra-worker

# Bootstrap ansible for CoreOS
- hosts: worker_nodes
  gather_facts: False
  roles:
    - defunctzombie.coreos-bootstrap

# Gather facts on all nodes
- hosts: all
  tasks: []

# Generate certificates
- hosts: localhost
  connection: local
  roles:
    - certificates

# Deploy kubernetes components for worker nodes
- hosts: worker_nodes
  become: true
  roles:
    - kubernetes-worker

# Write inventory
- hosts: localhost
  connection: local
  roles:
    - infra-inventory

# Setup kubectl and deploy sky-dns
- hosts: localhost
  connection: local
  roles:
    - kubectl
    - kube-dns
